insert into item (name, rate, category, owner_id) values ('Soup - Knorr, Chicken Gumbo', 699, 'AYOO', 4);
insert into item (name, rate, category, owner_id) values ('Duck - Fat', 193, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Mix Pina Colada', 605, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Yogurt - Blueberry, 175 Gr', 596, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Flour - Cake', 468, 'DAYMM', 4);
insert into item (name, rate, category, owner_id) values ('Sprouts - Corn', 396, 'DAYMM', 4);
insert into item (name, rate, category, owner_id) values ('Stock - Chicken, White', 462, 'PISS', 4);
insert into item (name, rate, category, owner_id) values ('Tomatoes - Vine Ripe, Yellow', 547, 'AYOO', 4);
insert into item (name, rate, category, owner_id) values ('Cheese - Woolwich Goat, Log', 513, 'ONO', 4);
insert into item (name, rate, category, owner_id) values ('Cheese - St. Paulin', 330, 'UWU', 4);
insert into item (name, rate, category, owner_id) values ('Turkey - Breast, Boneless Sk On', 436, 'AYOO', 4);
insert into item (name, rate, category, owner_id) values ('Wheat - Soft Kernal Of Wheat', 186, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Beef - Cooked, Corned', 634, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Parsley - Dried', 181, 'UWU', 4);
insert into item (name, rate, category, owner_id) values ('Water - Spring Water 500ml', 662, 'DAYMM', 4);
insert into item (name, rate, category, owner_id) values ('Nut - Pine Nuts, Whole', 603, 'ONO', 4);
insert into item (name, rate, category, owner_id) values ('Tea - Lemon Scented', 306, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Cafe Royale', 312, 'UWU', 4);
insert into item (name, rate, category, owner_id) values ('Assorted Desserts', 671, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Plate Foam Laminated 9in Blk', 529, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Barley - Pearl', 577, 'PISS', 4);
insert into item (name, rate, category, owner_id) values ('Wine - Conde De Valdemar', 519, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Shrimp - Black Tiger 13/15', 103, 'PISS', 4);
insert into item (name, rate, category, owner_id) values ('Butter Sweet', 306, 'DAYMM', 4);
insert into item (name, rate, category, owner_id) values ('Sweet Pea Sprouts', 622, 'AYOO', 4);
insert into item (name, rate, category, owner_id) values ('Cup - 6oz, Foam', 171, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Apricots - Dried', 199, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Thyme - Lemon, Fresh', 341, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Beef - Cooked, Corned', 923, 'DAYMM', 4);
insert into item (name, rate, category, owner_id) values ('Bread - Petit Baguette', 242, 'UWU', 4);
insert into item (name, rate, category, owner_id) values ('Island Oasis - Raspberry', 997, 'ONO', 4);
insert into item (name, rate, category, owner_id) values ('Soup - Campbells Pasta Fagioli', 442, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Mushroom - White Button', 672, 'ONO', 4);
insert into item (name, rate, category, owner_id) values ('Broccoli - Fresh', 855, 'OWO', 4);
insert into item (name, rate, category, owner_id) values ('Pears - Fiorelle', 963, 'DAYMM', 4);
insert into item (name, rate, category, owner_id) values ('Smoked Tongue', 912, 'AYOO', 4);
insert into item (name, rate, category, owner_id) values ('Cheese - Roquefort Pappillon', 423, 'ONO', 4);
insert into item (name, rate, category, owner_id) values ('Wine - Port Late Bottled Vintage', 859, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Veal - Round, Eye Of', 555, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Cheese - Valancey', 939, 'ONO', 4);
insert into item (name, rate, category, owner_id) values ('Pork - Side Ribs', 629, 'PISS', 4);
insert into item (name, rate, category, owner_id) values ('Wine - Segura Viudas Aria Brut', 159, 'ONO', 4);
insert into item (name, rate, category, owner_id) values ('Latex Rubber Gloves Size 9', 884, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Wine - Tio Pepe Sherry Fino', 401, 'PISS', 4);
insert into item (name, rate, category, owner_id) values ('Pop Shoppe Cream Soda', 586, 'DAYMM', 4);
insert into item (name, rate, category, owner_id) values ('Sauce - Demi Glace', 901, 'SHEESH', 4);
insert into item (name, rate, category, owner_id) values ('Muffin Hinge - 211n', 800, 'UWU', 4);
insert into item (name, rate, category, owner_id) values ('Dikon', 495, 'PISS', 4);
insert into item (name, rate, category, owner_id) values ('Pastry - Chocolate Marble Tea', 550, 'DAYMM', 4);
insert into item (name, rate, category, owner_id) values ('Raisin - Golden', 327, 'PISS', 4);
